### ISSUE TITLE
PHP Warning in v1.0.3

### ISSUE THREAD

**Issue by Tangol** [codexilab/osclass-banners#6]
Please note that I'm getting the following warning:
`PHP Warning: implode(): Invalid arguments passed in \oc-content\plugins\banners\controller\admin\set-banner.php on line 52`

Plugin v1.0.3
PHP 7.4.24

**Comment by Tangol** [comment]
Sorry, I forgot to add the steps to reproduce the issue.

1. Install the plugin
2. Go to **3 - Banners** -> **Add new Banner** (`/oc-admin/index.php?page=plugins&action=renderplugin&route=banners-admin-set`)
3. Set a date, add an image
4. Click **Add new banner**

Note: at point 3, no other fields should be filled in, as you need to get the error:  `All fields cannot be empty.`

Then you'll get a notice in debug.

**Comment by adrianolmedo** [comment]
I must admit that a validation of the fields with jquery is missing, which shades in red which ones are still to be filled, for now you will only know when you submit the form.

Always start by covering the most important, in this order:

- Positions
- Banners
- To
- Until
- URL
- Complete the rest ...

Make sure the new banner does not step on dates marked in an already occupied calendar range.

**Comment by adrianolmedo** [comment]
If you are testing some of my themes like [BenderBS](https://github.com/codexilab/osclass-benderbs) or [XTClass](https://github.com/codexilab/osclass-xtclass), you can be sure to paste PHP code in these sections:

Appearance » Theme settings

![https://i.imgur.com/1He6loq.png](https://i.imgur.com/1He6loq.png)

In this case I recommend to title the positions the size of the space, example **300x250** is cognitively easier to identify:

![https://i.imgur.com/UbxejDf.png](https://i.imgur.com/UbxejDf.png)

**Comment by Tangol** [comment]
> I must admit that a validation of the fields with jquery is missing, which shades in red which ones are still to be filled, for now you will only know when you submit the form.
> 
> Always start by covering the most important, in this order:
> 
> * Positions
> * Banners
> * To
> * Until
> * URL
> * Complete the rest ...
> 
> Make sure the new banner does not step on dates marked in an already occupied calendar range.

Thanks for the heads-up, however I was testing it like that on purpose to find out if there are any issues, notices/warnings that might indicate that something is not quite right in the code.

Still, the plugin is no less than awesome!
